### ISSUE TITLE
已Start,提个建议。

### ISSUE THREAD

**Issue by abbenyyyyyy** [yizhiwazi/springboot-socks#1]
任何学习配合快速出成果，都能使学习者获得满足感从而能继续下去。
所以我想向作者大佬提个建议，既然你已经写了springBoot的一系列文章，何不写一个从0部署到云服务器平台（阿里云之类的初始服务器）的指南，毕竟现在Android转后端的有点多，例如我，却不知道如何在云服务器上面从0部署...
总之，谢谢你的分享。

**Comment by yizhiwazi** [comment]
感谢建议，部署流程暂时没有列入本章的计划，目前网上已经有很多关于Docker容器部署和Jenkins持续集成的相关技术，你可以多去了解一下。（推荐一个学习社区：http://www.spring4all.com ，推荐书籍：《Spring Cloud与Docker微服务架构实战》作者也是社区的核心成员：周立。
