### ISSUE TITLE
多任务并发

### ISSUE THREAD

**Issue by wolf9236** [yizhiwazi/springboot-socks#11]
怎么样才能做到 多个任务并行？有N个任务，其中有几个任务执行时间比较长，导致其他任务没有按时间点执行

**Comment by Coder994** [comment]
【说明】springboot的定时任务默认是同步的，如果前面有个定时任务执行时间很长，会阻塞下一个定时任务，导致下一个任务无法按时执行（但仍然会执行）
【解决方法】在你的启动类贴上@EnableAsync，表明开启异步；接着到你定时任务类，再贴上@Async即可异步，所有定时任务都可按时执行

**Comment by yizhiwazi** [comment]
那要看业务是否有顺序，没有的话可以内部或者外部异步执行。
