### ISSUE TITLE
关于事务失效的问题

### ISSUE THREAD

**Issue by Tomcatkai** [yizhiwazi/springboot-socks#5]
你好,我在项目中使用了您提供的统一异常处理,但是我的事务却有时候会失效,在下小白一枚,请问您的这个工具会对spring中的事务产生影响吗?谢谢

**Comment by yizhiwazi** [comment]
ErrorController 只是处理全局控制层的异常而已对事务并无直接影响，事务未生效请查看@Service层是否加上了@Transactional注解 并且是遇到了非检测异常（即RuntimeException及其子类）和Error才会回滚，事务应该统一在业务层处理，在DAO层不应该加上事务注解。

**Comment by Tomcatkai** [comment]
嗯嗯,明白了,谢谢大佬 😄

**Comment by Tomcatkai** [comment]
嗯嗯,明白了,谢谢大佬 😄
