### ISSUE TITLE
是不是少了个@Service的注解？

### ISSUE THREAD

**Issue by xdcrazyboy** [yizhiwazi/springboot-socks#6]

**Comment by PiousJester** [comment]
我也不清楚0.0


发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: xdcrazyboy <notifications@github.com>
发送时间: Monday, July 15, 2019 4:40:03 PM
收件人: yizhiwazi/springboot-socks
抄送: Subscribed
主题: [yizhiwazi/springboot-socks] 是不是少了个@Service的注解？ (#6)


―

**Comment by yizhiwazi** [comment]
描述不清楚 建议下载原香项目启动
