### ISSUE TITLE
作者您好，udacity的Java开发工程师微学位课程的project1似乎是直接用了您的聊天室项目

### ISSUE THREAD

**Issue by fanhk** [yizhiwazi/springboot-socks#7]
https://github.com/udacity/JDND/tree/master/projects/P01-Chatroom/starter_code
这个是udacity的一个付费课程的project1，似乎是直接用了您spring-boot-websocket-chat的代码，前端都没改。不知道您是否知情

**Comment by yizhiwazi** [comment]
fanhk童鞋你好 我看了哪个优达学城的项目 完全是抄袭的 也没有注明原出处 最可恨的是把我的注解都给删了 注解是帮助新人快速学习的 这种行为确实可恶 我已经提ISSUE给对方人员了 感谢帮忙监督！
